### ISSUE TITLE
[scripts] Use LocalCKAN for importing contents

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/ckanext-odm_dataset#69]
_From @acorbi on February 5, 2015 14:17_

Insted of instantiating RemoteCkan within the scripts for import use https://github.com/ckan/ckanapi#localckan. It uses the default site user with full access ( no need to provide APIKEY)

_Copied from original issue: OpenDevelopmentMekong/ckanext-odm_utils#49_

**Comment by acorbi** [comment]
```
(ckan)vagrant@vagrant-ubuntu-trusty-64:~/.virtualenvs/ckan/src/ckanext-odm_utils/ckanext/odm_utils/scripts$ python insert_initial_odm_data.py
Traceback (most recent call last):
  File "insert_initial_odm_data.py", line 27, in <module>
    ckanapiutils = ckanapi_utils.LocalCkanApi()
  File "../utils/ckanapi_utils.py", line 263, in __init__
    self.api = ckanapi.LocalCKAN()
  File "/home/vagrant/.virtualenvs/ckan/src/ckanapi/ckanapi/localckan.py", line 19, in __init__
    username = self.get_site_username()
  File "/home/vagrant/.virtualenvs/ckan/src/ckanapi/ckanapi/localckan.py", line 25, in get_site_username
    user = self._get_action('get_site_user')({'ignore_auth': True}, ())
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/ckan/logic/__init__.py", line 419, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/ckan/logic/action/get.py", line 1963, in get_site_user
    user = model.User.get(site_id)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/ckan/model/user.py", line 61, in get
    return query.first()
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2156, in first
    ret = list(self[0:1])
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2023, in __getitem__
    return list(res)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2227, in __iter__
    return self._execute_and_instances(context)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2240, in _execute_and_instances
    close_with_result=True)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2231, in _connection_from_session
    **kw)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 727, in connection
    bind = self.get_bind(mapper, clause=clause, **kw)
  File "/home/vagrant/.virtualenvs/ckan/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 975, in get_bind
    ', '.join(context)))
sqlalchemy.exc.UnboundExecutionError: Could not locate a bind configured on mapper Mapper|User|user, SQL expression or this Session
```

According to wardi on http://webchat.freenode.net/?channels=ckan 
```LocalCKAN only works from ckan extensions and things like paster commands```
The code from the scripts would either need to be encapsulated to be called from within the extension's logic or the ckanapi CLI's logic should be replicated in the scripts.

**Comment by acorbi** [comment]
Fixed. Now import scripts are maintained under https://github.com/OpenDevelopmentMekong/ckanext-odm_migration which uses Ckanapi Local
